name: smart_parcel_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/
